fix(map.jinja): checksum GPG KEY for EPEL-8
saltstack-formulas/epel-formula pull request #61
Opened 2020-12-22 23:23 UTC by itscaro

same key as EPEL 7 but different checksum

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

### Describe the changes you're proposing

### Pillar / config required to test the proposed changes

### Debug log showing how the proposed changes work

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

2020-12-22 23:45 UTC, itscaro commented on epel/map.jinja
> +        'key': 'https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8',
The PR is to correct this GPG key, which is EPEL 7 instead of EPEL 8

2020-12-23 09:29 UTC, itscaro commented on epel/map.jinja
> +        'key_hash': 'sha256=028b9accc59bab1d21f2f3f544df5469910581e728a64fd8c411a725a82300c2',
```
gpg --with-fingerprint 352C64E5.txt
pub  4096R/352C64E5 2013-12-16 Fedora EPEL (7) <epel@fedoraproject.org>
      Key fingerprint = 91E9 7D7C 4A5E 96F1 7F3E  888F 6A2F AEA2 352C 64E5
```
```
gpg --with-fingerprint RPM-GPG-KEY-EPEL-7
pub  4096R/352C64E5 2013-12-16 Fedora EPEL (7) <epel@fedoraproject.org>
      Key fingerprint = 91E9 7D7C 4A5E 96F1 7F3E  888F 6A2F AEA2 352C 64E5
```

2020-12-23 09:39 UTC, myii commented
Thanks for working through the links, @itscaro.  I'd like to get a review from @ixs who had a big part in setting up the original structure of this file.  It make take some time because of the holidays but if you don't hear from us, please feel free to ping me.

2020-12-23 10:04 UTC, ixs commented
Thank you @myii. I had a quick look:

The change looks generally good and coincidentally is very similar to what I had locally but forgot to issue a PR for. 🤦🏻‍♂️
The SHA256SUM also looks good and is due to different representation of the GPG key on the fedoraproject site vs. the download site.

There's just one thing I'd like you to fix before approving. Please change the links from https://download.fedoraproject.org/ to https://dl.fedoraproject.org/.

The downloads vhost is serving a redirect to the mirror network. The dl vhost is the canonical master server. For something like the GPG signing key I'd prefer the canonical master without any mirrors in between that might break things in unexpected way.

2020-12-23 10:08 UTC, ixs requested changes

2020-12-23 10:08 UTC, ixs commented on epel/map.jinja
> +        'key': 'https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-5',
dl.fedoraproject.org please.

2020-12-23 10:08 UTC, ixs commented on epel/map.jinja
> +        'key': 'https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6',
same. dl.fedoraproject.org please.

2020-12-23 10:08 UTC, ixs commented on epel/map.jinja
> +        'key': 'https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7',
same. dl.fedoraproject.org please.

2020-12-23 10:08 UTC, ixs commented on epel/map.jinja
> +        'key': 'https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8',
same. dl.fedoraproject.org please.

2020-12-23 14:45 UTC, myii commented
Really appreciate the prompt review, @ixs.  Excellent feedback, too.

2020-12-25 11:48 UTC, ixs approved these changes
@itscaro Thank you very much. Looks good.

2020-12-25 11:48 UTC, itscaro commented
@ixs Thank you for the feedback, I switch to dl.fedoraproject.org :-)

Happy holidays!

2020-12-25 11:49 UTC, ixs commented
@itscaro merry christmas or whatever floats your sled. 😂

2020-12-25 19:59 UTC, myii approved these changes

2020-12-25 19:59 UTC, merged

2020-12-25 20:00 UTC, myii commented
A nice, tidy PR -- thanks guys!  Merged.